import { BaseClass } from '../../../lib/objects/BaseClass.js';
import { computeCitation as computeCitationForFields } from '../../citation/citation-engine.js';
import { resolveLibraryNote } from '../controls/resolve-library.js';
import { resolveNoteFile } from '../controls/resolve-note-file.js';
import {
	resolveNoteLinkLenient,
	resolveNoteLinksLenient,
	toWikilink,
} from '../controls/resolve-titles.js';
import { appendToFrontmatterArray } from '../controls/append-to-frontmatter-array.js';

// Shared middle tier for every Library "works" class. Owns the fields
// common to all Works leaves and folder resolution shared by all 11
// leaves. Citation-generation itself now lives in citation-engine.js as
// a standalone function -- this class only supplies the leaf's own
// app/path/folder/classValue to it, so non-Works classes (e.g.
// Collection) can call the same function without inheriting from
// Works.
export class Works extends BaseClass {
	constructor(app, options = {}) {
		super(app, options);

		this.sortTitle = deriveSortTitle(this.filename);

		// The tag scoping this note's library, read off the library
		// note's own frontmatter -- used to scope the Dashboard queries
		// to just this library's works, matching Library.js's own
		// dashboard query pattern.
		this.libraryTag = app.metadataCache.getFileCache(resolveLibraryNote(app, this.folder))?.frontmatter?.['library-tag'] ?? '';

		this.authors = options.authors ?? [];
		this.editors = options.editors ?? [];
		this.translators = options.translators ?? [];
		this.year = options.year ?? '';
		this.collections = options.collections ?? [];
		this.edition = options.edition ?? '';
		this.publisher = options.publisher ?? '';
		this.placeOfPublication = options.placeOfPublication ?? '';
		this.textSource = options.textSource ?? '';
		this.abstract = options.abstract ?? '';
		this.catalogStatus = options.catalogStatus ?? '';
		this.dateConsumed = options.dateConsumed ?? '';
		this.dateCataloged = options.dateCataloged ?? '';
		this.dateReviewed = options.dateReviewed ?? '';
		this.wordCount = options.wordCount ?? '';
		this.themes = options.themes ?? [];
		this.keywords = options.keywords ?? [];
		this.contentWarnings = options.contentWarnings ?? [];
		this.cites = resolveNoteLinksLenient(app, this.path, options.cites ?? []);
		this.related = resolveNoteLinksLenient(app, this.path, options.related ?? []);
		this.partOf = resolveNoteLinkLenient(app, this.path, options.partOf ?? '');
		this.context = resolveNoteLinksLenient(app, this.path, this.context);

		// Set by leaf subclasses via computeCitation() after their own
		// citation-relevant fields are assigned.
		this.citation = '';
	}

	// Computes this Works instance's citation via the citation engine,
	// resolving the governing style from the parent Library note
	// first. Leaf subclasses call this from their own constructor,
	// after super() and after their own citation-relevant fields are
	// assigned, since `fields` is leaf-specific. The leaf class itself
	// is read off `this.constructor.classValue`.
	computeCitation(fields) {
		return computeCitationForFields(
			this.app,
			this.path,
			this.folder,
			this.constructor.classValue,
			fields
		);
	}

	// Composes the note body from the four sub-methods below, in fixed
	// order. Leaves override only the sub-method(s) that vary; most
	// override none. filter(Boolean) drops a section that returns an
	// empty string (e.g. an unused getBodyAccessory()) rather than
	// leaving a blank gap in the compiled body.
	getBody() {
		return [
			this.getBodyIntroduction(),
			this.getBodyDashboard(),
			this.getBodyAccessory(),
			this.getBodyFreeform(),
		].filter(Boolean).join('\n\n');
	}

	// No-op by default. Positioned between the Dashboard and Freeform
	// sections -- a leaf overrides this when it needs a structured
	// section surfaced immediately after the computed cross-references,
	// before the open curator space in Freeform.
	getBodyAccessory() {
		return '';
	}

	// Computed cross-reference tables, scoped to this note's library
	// via the library-tag resolved at construction (this.libraryTag),
	// matching Library.js's own dashboard query pattern.
	getBodyDashboard() {
		return `## catalog queries
---

### cited by this work

\`\`\`dataview
TABLE WITHOUT ID
    file.link AS "Work",
    authors AS "Author(s)",
    year AS "Year",
    catalog-status AS "Status"
FROM
	#${ this.libraryTag } AND
	#catalog-works
WHERE
	contains(this.cites, file.link)
SORT
	year ASC
\`\`\`

### what cites this work

\`\`\`dataview
TABLE WITHOUT ID
    file.link AS "Cited In",
    authors AS "Author(s)",
    year AS "Year"
FROM
	#${ this.libraryTag } AND
	#catalog-works
WHERE
	contains(cites, this.file.link)
SORT
	year ASC
\`\`\`

### unread placeholders generated by this work

\`\`\`dataview
TABLE WITHOUT ID
    file.link AS "Work",
    year AS "Year"
FROM
	#${ this.libraryTag } AND
	#catalog-works
WHERE
	contains(this.cites, file.link) AND
	catalog-status = "placeholder"
SORT
	file.name ASC
\`\`\`

### works by the same author(s)

\`\`\`dataview
TABLE WITHOUT ID
    file.link AS "Work",
    year AS "Year",
    catalog-status AS "Status"
FROM
	#${ this.libraryTag } AND
	#catalog-works
WHERE
	authors AND
	any(authors, (a) => contains(this.authors, a)) AND
	file.name != this.file.name
SORT
	year ASC
\`\`\`

### related works

\`\`\`dataview
TABLE WITHOUT ID
    file.link AS "Work",
    authors AS "Author(s)",
    year AS "Year",
    catalog-status AS "Status"
FROM
	#${ this.libraryTag } AND
	#catalog-works
WHERE
	(related AND contains(this.related, file.link)) OR
	(themes AND any(themes, (t) => contains(this.themes, t)))
SORT
	file.name ASC
\`\`\`

### terms

\`\`\`dataview
TABLE WITHOUT ID
    file.link AS "Term"
FROM
	#${ this.libraryTag }
WHERE
	class = "definition" AND
	contains(reference-work, this.file.link)
SORT
	file.name ASC
\`\`\`
`;
	}

	// Open catch-all. Guaranteed to contain notes; a leaf may add
	// further headings here that have no specific positional need.
	getBodyFreeform() {
		return `## notes
---


`;
	}

	// Fixed lead section every leaf carries, no exceptions.
	getBodyIntroduction() {
		return `## Summary
---


`;
	}

	// Performs this Works instance's Accession pushes -- see the
	// Accession Specification for the full trigger map. Resolves every
	// Author wikilink across all five role fields (authors, editors,
	// translators, interviewer, interviewee) and pushes this note into
	// each resolved Author's works array, and each of this note's
	// linked Collections into each resolved Author's collections
	// array. Then, for each linked Collection, pushes this note into
	// the Collection's works array and this note's authors into the
	// Collection's authors array, repeating the authors push into that
	// Collection's Periodical when one is set.
	async postCreate(file) {
		await super.postCreate(file);

		const workLink = toWikilink(this.filename);

		const authorFiles = [
			...this.authors,
			...this.editors,
			...this.translators,
			...(this.interviewer ?? []),
			...(this.interviewee ?? []),
		].map(
			(rawAuthor) => resolveNoteFile(
				this.app,
				this.path,
				rawAuthor
			)
		);

		const collectionFiles = this.collections.map(
			(rawCollection) => resolveNoteFile(
				this.app,
				this.path,
				rawCollection
			)
		);

		for (const authorFile of authorFiles) {
			await appendToFrontmatterArray(
				this.app,
				authorFile,
				'works',
				workLink
			);

			for (const collectionFile of collectionFiles) {
				await appendToFrontmatterArray(
					this.app,
					authorFile,
					'collections',
					toWikilink(collectionFile.basename)
				);
			}
		}

		for (const collectionFile of collectionFiles) {
			await appendToFrontmatterArray(
				this.app,
				collectionFile,
				'works',
				workLink
			);

			for (const author of this.authors) {
				await appendToFrontmatterArray(
					this.app,
					collectionFile,
					'authors',
					author
				);
			}

			const periodicalLink = this.app.metadataCache.getFileCache(collectionFile)?.frontmatter?.periodical;
			if (periodicalLink) {
				const periodicalFile = resolveNoteFile(
					this.app,
					this.path,
					periodicalLink
				);
				for (const author of this.authors) {
					await appendToFrontmatterArray(
						this.app,
						periodicalFile,
						'authors',
						author
					);
				}
			}
		}
	}

	// Resolves the enclosing library's works folder from the active file's
	// location: <libraryFolder>/<works-folder-name>, reading
	// works-folder-name off the library note and falling back to `works`
	// when the field is blank or missing. Throws if the active file isn't
	// inside a library. Inherited by every Works leaf.
	static async resolveFolder(app) {
		const startFolderPath = app.workspace.getActiveFile()?.parent?.path ?? '';
		const libraryNote = resolveLibraryNote(app, startFolderPath);
		const libraryFolder = libraryNote.parent?.path ?? '';
		const worksFolderName = app.metadataCache.getFileCache(libraryNote)?.frontmatter?.['works-folder-name'] || 'works';
		return `${ libraryFolder }/${ worksFolderName }`;
	}

	// Values shared across every Works leaf, gathered here so
	// subclasses can splice them into their own getFrontmatterFields()
	// in whatever key order their schema calls for.
	worksFrontmatterFields() {
		return {
			'sort-title': this.sortTitle,
			authors: this.authors,
			editors: this.editors,
			translators: this.translators,
			year: this.year,
			collections: this.collections,
			edition: this.edition,
			publisher: this.publisher,
			'place-of-publication': this.placeOfPublication,
			citation: this.citation,
			'text-source': this.textSource,
			abstract: this.abstract,
			'catalog-status': this.catalogStatus,
			'date-consumed': this.dateConsumed,
			'date-cataloged': this.dateCataloged,
			'date-reviewed': this.dateReviewed,
			'word-count': this.wordCount,
			themes: this.themes,
			keywords: this.keywords,
			'content-warnings': this.contentWarnings,
			cites: this.cites,
			related: this.related,
			'part-of': this.partOf,
		};
	}
}

// "The Unbearable Lightness of Being" -> "Unbearable Lightness of Being"
// Strips a single leading English article.
function deriveSortTitle(filename) {
	return filename.replace(/^(a|an|the)\s+/i, '');
}